# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frm_prueba_estilo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmPruebaEstilo(object):
    def setupUi(self, frmPruebaEstilo):
        frmPruebaEstilo.setObjectName("frmPruebaEstilo")
        frmPruebaEstilo.resize(400, 326)
        self.pushButton = QtWidgets.QPushButton(frmPruebaEstilo)
        self.pushButton.setGeometry(QtCore.QRect(110, 130, 161, 71))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(frmPruebaEstilo)
        QtCore.QMetaObject.connectSlotsByName(frmPruebaEstilo)

    def retranslateUi(self, frmPruebaEstilo):
        _translate = QtCore.QCoreApplication.translate
        frmPruebaEstilo.setWindowTitle(_translate("frmPruebaEstilo", "Form"))
        self.pushButton.setText(_translate("frmPruebaEstilo", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frmPruebaEstilo = QtWidgets.QWidget()
    ui = Ui_frmPruebaEstilo()
    ui.setupUi(frmPruebaEstilo)
    frmPruebaEstilo.show()
    sys.exit(app.exec_())
